name: Run Jest Tests

on:
  push:
    branches:
      - main

jobs:
  Jest:
    runs-on: ubuntu-latest
    environment: test
    env:
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY}}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL}}
      SUPABASEURL: ${{ secrets.SUPABASE_URL}}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Tests
        run: |
          npm install
          npm run build 
          npm run test
